config/routes.rb
Rails.application.routes.draw do
  resources :concepts
  devise_for :users
  resources :users
  root 'concepts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concept.rb
class Concept < ApplicationRecord

  has_many :notes
  accepts_nested_attributes_for :notes

end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :concept
  # validates_presence_of :note

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController
  before_action :set_concept, only: [:show, :edit, :update, :destroy]

  # GET /concepts
  # GET /concepts.json
  def index
    # @concepts = Note.includes(:concept)
    @concepts = Concept.includes(:notes)


  end

  # GET /concepts/1
  # GET /concepts/1.json
  def show

  end

  # GET /concepts/new
  def new
    @concept = Concept.new
  end

  # GET /concepts/1/edit
  def edit
  end

  # POST /concepts
  # POST /concepts.json
  def create
    @concept = Concept.new(concept_params)

    respond_to do |format|
      if @concept.save
        format.html { redirect_to '/concepts', notice: 'Concept was successfully created.' }
        format.json { render :show, status: :created, location: @concept }
      else
        format.html { render :new }
        format.json { render json: @concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concepts/1
  # PATCH/PUT /concepts/1.json
  def update
    respond_to do |format|
      if @concept.update(concept_params)
        format.html { redirect_to @concept, notice: 'Concept was successfully updated.' }
        format.json { render :show, status: :ok, location: @concept }
      else
        format.html { render :edit }
        format.json { render json: @concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concepts/1
  # DELETE /concepts/1.json
  def destroy
    @concept.destroy
    respond_to do |format|
      format.html { redirect_to concepts_url, notice: 'Concept was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concept
      @concept = Concept.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concept_params
      params.require(:concept).permit(:name, :stage, :dvf, :current_valuation, :future_valuation, :notes_attributes => [:id, :title, :description])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concepts_helper.rb
module ConceptsHelper
  def setup_concept(concept)
    notes = concept.notes
    notes.present? ? notes : 3.times {notes.build}
    concept
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/concepts/_form.html.erb
<%= form_with(model: setup_concept(concept), local: true) do |form| %>
  <% if concept.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(concept.errors.count, "error") %> prohibited this concept from being saved:</h2>

      <ul>
      <% concept.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :concept_name %>
  </div>

  <div class="field">
    <%= form.label :stage %>
    <%= form.text_field :stage, id: :concept_stage %>
  </div>

  <div class="field">
    <%= form.label :dvf %>
    <%= form.text_field :dvf, id: :concept_dvf %>
  </div>

  <div class="field">
    <%= form.label :current_valuation %>
    <%= form.number_field :current_valuation, id: :concept_current_valuation %>
  </div>

  <div class="field">
    <%= form.label :future_valuation %>
    <%= form.number_field :future_valuation, id: :concept_future_valuation %>
  </div>
  <%= form.fields_for :notes do |ff| %>
      <div>
        <%= ff.label :title %>
        <%= ff.text_field :title %>
      </div>
  <% end %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/concepts/edit.html.erb
<h1>Editing Concept</h1>

<%= render 'form', concept: @concept %>

<%= link_to 'Show', @concept %> |
<%= link_to 'Back', concepts_path %>

app/views/concepts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Concepts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Stage</th>
      <th>Dvf</th>
      <th>Current valuation</th>
      <th>Future valuation</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concepts.each do |concept| %>
      <tr>
        <td><%= concept.name %></td>
        <td><%= concept.stage %></td>
        <td><%= concept.dvf %></td>
        <td><%= concept.current_valuation %></td>
        <td><%= concept.future_valuation %></td>
        <td><%= concept.notes %></td>
        <td><%= link_to 'Show', concept %></td>
        <td><%= link_to 'Edit', edit_concept_path(concept) %></td>
        <td><%= link_to 'Destroy', concept, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Concept', new_concept_path %>

app/views/concepts/new.html.erb
<h1>New Concept</h1>

<%= render 'form', concept: @concept %>

<%= link_to 'Back', concepts_path %>

app/views/concepts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @concept.name %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @concept.stage %>
</p>

<p>
  <strong>Dvf:</strong>
  <%= @concept.dvf %>
</p>

<p>
  <strong>Current valuation:</strong>
  <%= @concept.current_valuation %>
</p>

<p>
  <strong>Future valuation:</strong>
  <%= @concept.future_valuation %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @concept.notes %>
</p>

<%= link_to 'Edit', edit_concept_path(@concept) %> |
<%= link_to 'Back', concepts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zxventures</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>